refactor: changed webpack to vite, added chakra ui + eslint new rules
UTBM-FISA-TutoredProject/Frontend pull request #3
Opened 2022-12-09 08:25 UTC by ayoubqrt

Changed Vite to webpack
replaced mui with chakra ui
changed some annoying eslint rules

2022-12-09 09:45 UTC, Valentin271 requested changes
A toi de voir si tu laisse le pnpm-lock, je pense que c'est inutile, garde le juste pour toi.

Si tu peux remettre le yarn-lock, la plupart l'utiliseront via docker.

2022-12-09 09:45 UTC, Valentin271 commented on .gitignore
> +!.vscode/extensions.json
Possiblblement ne pas partager les extensions vscode, tout le monde ne veut pas les mêmes.

```suggestion
.vscode
```

2022-12-09 09:45 UTC, Valentin271 commented on .nvmrc
> +16.18.0
Je pense que le nvmrc est inutile, possiblement à ajouter au gitignore

2022-12-09 09:45 UTC, Valentin271 commented on README.md
> +### `pnpm run lint`
Tu peux rollback le readme, la plupart utilisera yarn dans le docker.
Les descriptions aiderons les apprenants.

2022-12-09 09:45 UTC, Valentin271 commented on package.json
> +    "framer-motion": "^7.6.19",
On a décider d'utiliser MUI par vote.

2022-12-09 10:58 UTC, Kroissan commented on .eslintrc
> +    "semi": ["error", "always"],
svp pas besoin les règles sont trop stricts

2022-12-09 11:13 UTC, Valentin271 commented on .eslintrc
> +    "semi": ["error", "always"],
C'est littéralement les règles les plus importantes, en plus je vois pas en quoi ça gène c'est formaté automatiquement ça.
Il faut justement que ce soit stricte, tout le monde ne sait pas faire et il faut avoir le meme style de codage.

2022-12-11 13:56 UTC, ayoubqrt commented on .eslintrc
> +    "semi": ["error", "always"],
@Kroissan c'est quoi qui te dérange dans ces 4 règles ? les points-virgules c'est un choix et je trouve que c'est un peu bête de l'enlever même si ça marche sans en soit. L'indentation c'est incroyable de mettre une règle parce que si chacun formatte à sa façon le code, le code sera pas trop lisible, au taf on a pas de linter et ça fout le seum quand tu vois la gueule du code. Et voilà t'utilise prettier tu ctrl+s et ton code est formatté automatiquement et ton cerveau te remercie mdrr

2022-12-12 19:43 UTC, Valentin271 commented
J'ai ajouté vite et changé les règles eslint sur main, je te propose de fermer cette PR et si tu as d'autres modifications à proposer d'en refaire une.

2022-12-13 06:23 UTC, ayoubqrt commented
stp la prochaine fois ne ferme pas la pull request, l'intérêt d'une PR c'est que le code peut changer et que je peux le rebase. Ma PR s'occupait de vite et d'eslint, pourquoi avoir fait de ton côté les changements ? 
J'ai pas forcément eu le temps mais c'était prévu que je le fasse et on est pas pressés.

2023-02-07 14:05 UTC, closed without merging